name: ethereum_util
description: a collection of utility functions for Ethereum
version: 3.0.3
homepage: https://github.com/ethereumdart/ethereum_util

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  meta: ^1.3.0
  convert: ^3.0.1
  pointycastleold: 
    git:
      url: https://github.com/Quppy/pointycastle.git
      version: 1.0.3

  buffer: ^1.1.1
  equatable: ^0.2.3
  collection: ^1.15.0
  json_annotation:
  quiver: ^3.0.1+1

dev_dependencies:
  build_runner:
  json_serializable:
  path:
  test:
