name: ethereum_util
description: a collection of utility functions for Ethereum
version: 3.0.2
homepage: https://github.com/ethereumdart/ethereum_util

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  meta: ^1.3.0
  convert: ^3.0.1
  pointycastle: ^3.5.1
  buffer: ^1.1.1
  equatable: ^2.0.3
  collection: ^1.15.0
  json_annotation:
  quiver: ^3.0.1+1

dev_dependencies:
  build_runner:
  json_serializable:
  path:
  test:
